project:
  type: website
  output-dir: docs

website:
  title: "מבוא למדעי הרוח הדיגיטליים / שי גורדין"
  navbar:
    right:
      - href: index.qmd
        text: עמוד הבית
      - href: about.qmd
        text: תכנית הקורס
      - href: assignments.qmd
        text: מטלות

format:
  html:
    include-in-header:
      - text: |
          <link rel="preconnect" href="https://fonts.googleapis.com">
          <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
          <link href="https://fonts.googleapis.com/css2?family=Alef:wght@400;700&display=swap" rel="stylesheet">
    theme: cosmo
    css: styles.css
    toc: true
    toc-title: "בעמוד זה"
    html-metadata:
      lang: he
      dir: rtl
      


