---
title: "רשימת מקורות"
---

1.  איתי מרינברג-מיליקובסקי (2022) **מילים שקולות: צעדים ראשונים במחקר הספרות החישובי**, רעננה: האונ׳ הפתוחה.

2.  איתי מרינברג-מיליקובסקי ואופיר מינץ-מנור, עורכים (2022) **מחקר חישובי במדעי הרוח: אסופת מאמרים**, רעננה: האונ׳ הפתוחה.

3.  Arnold, Taylor, and Lauren Tilton. 2023. Distant Viewing: Computational Exploration of Digital Images. The MIT Press.[ https://doi.org/10.7551/mitpress/14046.001.0001](https://doi.org/10.7551/mitpress/14046.001.0001). Open access, download here: <https://direct.mit.edu/books/oa-monograph/5674/Distant-ViewingComputational-Exploration-of>  

4.  Blaney, J., Milligan, S., Steer, M., and Winters, J. (2021). Doing digital history, Manchester: Manchester University Press. <https://doi.org/10.7765/9781526157713>; The book\'s accompanying GitHub: <https://github.com/ihr-digital/digital-history>

5.  Drucker, J. (2021). The Digital Humanities Coursebook: An Introduction to Digital Methods for Research and Scholarship. Milton: Taylor & Francis. <https://ariel.primo.exlibrisgroup.com/permalink/972ARIEL_INST/2vc4mm/alma994272343507236> 

6.  Grimmer, Justin, Margaret E. Roberts, and Brandon M. Stewart. (2022). Text as Data: A New Framework for Machine Learning and the Social Sciences. Princeton: Princeton University Press.

7.  Guldi, Jo. (2023). The Dangerous Art of Text Mining: A Methodology for Digital History. Cambridge: Cambridge University Press.[ https://doi.org/10.1017/9781009263016](https://doi.org/10.1017/9781009263016).

8.  Manovich, Lev. 2020. Cultural Analytics. Cambridge, Massachusetts London, England: The MIT Press. The author\'s homepage with book download link: <https://manovich.net/index.php/projects/cultural-analytics> 

9.  McGillivray, Barbara, and Gábor Mihály Tóth. (2020). Applying Language Technology in Humanities Research: Design, Application, and the Underlying Logic. Cham: Springer International Publishing AG. <https://ariel.primo.exlibrisgroup.com/permalink/972ARIEL_INST/2vc4mm/alma994163453407236>

**לעיון דקדקני בחידושים בתחום לימודי היהדות הדיגיטליים:**

10. Zaagsma, Gerben, Stökl Ben Ezra, Daniel, Rürup, Miriam, Margolis, Michelle and Levi, Amalia S. (2022) Jewish Studies in the Digital Age, Berlin: De Gruyter. <https://doi.org/10.1515/9783110744828>

\
**רשימות כתבי העת במר״ד מתעדכנות כל העת, ראו למשל**: <https://dhjournals.github.io/list>; לדוגמא, כתב העת EPJ Data Science מכיל מאמרים רבים בתחומי מדעי החברה והרוח או כאלה שנושקים לתחום. ראו למשל את אסופת המאמרים: [The Past, Present, and Future of Computational Social Science](https://epjdatascience.springeropen.com/ppfcss).
