---
title: "קריאה רחוקה באמצעות Voyant Tools"
---

נא לקרוא את המאמר: [רוקוול וסינקלייר 2016](https://drive.google.com/file/d/11I1_Lduv1d43Ti88_4X1fAqh8-luR4gz/view?usp=sharing){target="_blank"}. לאחר מכן גשו לטופס המשימה [בקישור הבא](https://forms.gle/fS92Pk8KNgKkVafy9){target="_blank"} וענו שם על השאלות הבאות והסעיפים שלאחר מכן:

-   אנא נסו לסכם במילים שלכם מהי שאלת המחקר של המאמר?

-   אלו טרנספורמציות עובר טקסט שמוכנס לתוכנת וויאנט?

-   במה שונה קריאה של טקסט כנתונים מקריאה ״קרובה״?

נא לבחור כמה שיותר קבצי נתונים הנוגעים לפרויקט שתרצו לעשות בקורס מסוג טקסט פשוט או טבלה בצורת טקסט ולהעלות אותם לאתר [Voyant Tools](https://voyant-tools.org/). 

**טקסט פשוט** - txt (plain text files)

**טבלה בצורת טקסט** - cvs (comma separated values)

לאחר שתריצו את האפליקציה, יופיע לכם אתר פרויקט חדש שמציג ניתוח ויזאולי של המידע הטקסטואלי שהזנתם. נא להדביק למטה בשדה התשובה את **הקישור לקורפוס** שלכם שמופיע בשורת הכתובת האינטרנטית בראש הדפדפן. ככה אני אוכל לגשת ולראות מה עשיתם

למשל ראו דוגמא לקורפוס שנסתכל עליו בשיעור:

Sinclair, S. & G. Rockwell. (2024). Voyant Tools. *Voyant Tools*. Retrieved November 20, 2024, [https://voyant-tools.org/?panels=cirrus%2Creader%2Ctrends%2Csummary%2Ccontexts&corpus=84a1f3a26361c2bd475db4231d378cf1](https://voyant-tools.org/?panels=cirrus%2Creader%2Ctrends%2Csummary%2Ccontexts&corpus=84a1f3a26361c2bd475db4231d378cf1){target="_blank"}

שחקו עם הכלים השונים בוויאנט וחקרו את הטקסטים שלכם. האם גיליתם משהו מעניין שלא ידעתם קודם? האם גיליתם משהו שחשדתם בו או ידעתם אותו קודם אבל עכשיו ראיתם אותו בבירור דרך הויזואליזציות של וויאנט?

כתבו זאת במסמך וצרפו קישורים לוויזואליזציות או צילומי מסך. אתם יכולים לכתוב את המסמך בתוכנת וורד, אבל העלו אותה לכאן בבקשה **לאחר שהפכתם** את המסמך לקובץ PDF.
