---
title: "חובות ומטלות הקורס"
---

מרכיבי הציון הסופי: קריאת מאמרים והשתתפות בשיעור (10%), תרגילים שבועיים (20%), הצגה בכיתה (30%), ופוסטר מחקרי (40%). הקורס מורכב משלוש יחידות נושאיות הקשורות זו בזו ובונות לתמונה רחבה של התחום, כך שבכל שיעור כמעט יש קריאה כלשהי, פעילות בשיעור וכן ארבע מטלות להגשה. הפרויקט גמר של הקורס הוא פוסטר מחקרי שהציון עליו מבוסס על שתי הצגות והפוסטר עצמו: הצגת בזק של הנושא בסוף יחידה 1 של הקורס (28/11), והצגה סופית של המחקר והפוסטר בסוף הקורס שלאחריו יהיה שבוע בלבד כדי להגיש את הפוסטר מתוקן בגרסתו לקבלת הערכה סופית. ראה מבט על [בתכנית הקורס](/about.qmd){target="_blank"}, וגם בדפי מטלות באתר זה.

## קריאת מאמרים והשתתפות בשיעור (10%)

כמעט כל שיעור מכיל קריאה כלשהי שקשורה לפעילות שלנו באותו השבוע, ועל כן **יש לקרוא את המאמר לצרכי דיון בכיתה**. יש להגיע לכיתה מוכנים לדיון ולהשתתפות פעילה בו. לעתים אני מציין שהמאמר הוא לקריאה נוספת או להרחבה, ואז כמובן שקריאת המאמר היא רשות. כמו כן תרגולים בשיעור יערכו באמצעות תוכנות שלא מצריכות התקנה היישר מהדפדפן ו**השתתפות בתרגילים הללו** חשובה ללימוד מוצלח של הנושא.

## תרגילים שבועיים (20%)

ישנם ארבעה תרגילים המלמדים פרקטיקות חישוביות חיוניות למחקר בסיסי שחייבים להגיש בתאריכים הנקובים [בתכנית הקורס](/about.qmd){target="_blank"} והם כוללים:

1.  ניתוח פרויקט דיגיטלי ומאגר נתונים לבחירתכם, לפחות אחד מכל סוג (פרויקט אחד ומאגר נתונים אחד). את הפרויקטים ומאגרי הנתונים אפשר לבחור מתוך שדה המחקר המוכר לכם, או מתוך רשימת אתרים נתונה מראש. לפרטים נוספים וכיצד להגיש ראו [עמוד המטלה](/assignments/proj-analysis.qmd){target="_blank"}. ההגשה היא עד **תאריך 14/11** וייערך עליה דיון כיתתי מעמיק.

2.  קריאת יצירה ספרותית או טקסט אחר לבחירתכם באמצעות תוכנת [Voyant tools](https://voyant-tools.org/){target="_blank"}. הטקסט יכול להיות קשור לפרויקט גמר של הקורס, למחקר שלכם, או לכל דבר אחר שתרצו. עדיפות לטקסטים יחסית ארוכים, אבל יכול להיות גם הרבה טקסטים קצרים למשל. לפרטים נוספים וכיצד להגיש ראו [עמוד המטלה](/assignments/distant-reading.qmd){target="_blank"}. ההגשה היא עד **תאריך 12/12**.

3.  המרת טקסט מתמונה של מסמך לטקסט קריא למכונה (machine readable) באמצעות עיבוד תווים אופטי או OCR של תכנת [Tesseract OCR](https://tesseract-ocr.github.io/tessdoc/User-Projects-%E2%80%93-3rdParty.html){target="_blank"}. יש להכין לפחות שני עמודים ולבדוק אותם מול המקור, אנא תעדו את הטעויות וספרו אותן בטבלה. לפרטים נוספים וכיצד להגיש ראו [עמוד המטלה](/assignments/ocr.qmd){target="_blank"}. ההגשה היא עד **תאריך 19/12**.

4.  תיוג והעשרה של נתונים בטקסטים שעברו דיגיטציה בעזרת תוכנת [Recogito](https://recogito.pelagios.org/){target="_blank"}. רצוי לבחור חומרי מקור הקשורים לפרויקט הגמר שלכם במידת האפשר. לפרטים נוספים וכיצד להגיש ראו [עמוד המטלה](/assignments/markup.qmd){target="_blank"}. ההגשה היא עד **תאריך 2/1**.

## הצגה בכיתה (30%)

כבר בתחילת הקורס אתם נדרשים לבחור נושא לפוסטר המחקרי שהוא פרויקט הגמר מכיוון שיידרש זמן למחקר והכנה של הפרויקט. כדי לעשות זאת בצורה יעילה אתם נדרשים להציג את הנושא כבר בסוף יחידה 1 (28/11) בהצגת בזק (lightning talk) שתארך 7 דק׳ עם דיון באורך של 7 דק׳. הפידבק להרצאה יהיה מהתלמידים האחרים בשיעור בנוסף למרצה. להסבר נוסף על אופי ההרצאה ראו [עמוד פרויקט הגמר](/assignments/poster.qmd){target="_blank"}.

ההמשך בבניה!

## פוסטר מחקרי (40%)

בבניה!
