---
title: "פרויקט גמר: כרזה מדעית והצגתה בכיתה"
---

## הצגת בזק

### מטרת הפעילות:

להציג את נושא המחקר של הפוסטר שלכם אחד באופן תמציתי, ממוקד ומעניין במסגרת זמן קצובה של 7 דקות. **יש להודיע לי על הנושא שבחרתם בהקדם**. רצוי שהנושא יהיה קשור לתחום המחקר שלכם או נושא שאתם מלאי תשוקה לגביו, וכן ניתן גם להתייעץ איתי במייל.

### הנחיות כלליות:

ניתן להציג באופן יחידני או בזוגות יש להכין מצגת קצרה ותמציתית: ניתן להשתמש ב-PowerPoint, Google Slides, Canva. המצגת צריכה להיות מינימליסטית עם דגש על תמונות ומעט טקסט. המצגת תועבר למרצה **לפחות יומיים** לפני מועד ההצגה (26/11 בחצות).

### מבנה המצגת:

1.  שקופית פתיחה: כותרת הנושא ושמות המציגים

2.  בין 4 ל-5 שקופיות תוכן

3.  שקופית סיכום

### טיפים להצגה מוצלחת

בחרו נושא מתוך המאמר שניתן להציג כסיפור מעניין והשתמשו בתמונות איכותיות להמחשה. תרגלו את ההצגה מראש כדי לעמוד בזמנים הקפידו על מבנה ברור: פתיחה, גוף, סיכום.

### לוח זמנים

[זמן הצגה]{.underline}: 7 דקות בדיוק, יינתן אות התראה דקה לפני סיום. בתום ההצגה יתקיים דיון קצר ומשוב עמיתים.

### הערכה ומשוב

סטודנטים נבחרים יתבקשו לתת [משוב מובנה למציגים](https://forms.gle/AFrhcEoSGi5MeBTn6){target="_blank"} המשוב יתמקד בתוכן, אופן ההצגה ועמידה בזמנים בסיום כל הצגה יתקיים דיון קצר בכיתה. **חובה לקרוא** לפני השיעור את [Walsh 2023](https://dhdebates.gc.cuny.edu/read/what-we-teach-when-we-teach-dh/section/fdb7ea0a-5c9e-404a-ab9d-3a24fe6de61c#ch18){target="_blank"} כדי שנוכל לקיים דיון פדגוגי נאות.

### הגשה

יש להעלות את המצגת ל[קישור הבא](https://forms.gle/Suwtosy4wguUX5GE9){target="_blank"} לפי ההוראות ששם עד **לתאריך 26/11 בחצות**. שם הקובץ: LightningTalk_שם_משפחה.

### לוח זמנים להצגות

[ההצגות יתקיימו בתאריכים]{.underline}: 28/11 (ובמידת הצורך גם ה-5/12) סדר המציגים יפורסם שבוע לפני מועד ההצגות.

בהצלחה!

## הצגה לפני הגשה

### מועדי הצגה: 16/01/2025 או 23/01/2025

נא להירשם לתאריך הצגה בכיתה [בטופס שבקישור הבא](https://forms.gle/CXpwnEwzGxpYdNNw5){target="_blank"}. שימו לב! הרישום הוא על בסיס [כל הקודם זוכה]{.underline}. הצגת הפרויקט בכיתה הינה חלק משמעותי מפרויקט הגמר של הקורס ומהווה חלק מהציון של פרויקט הגמר. ההצגה תתקיים באופן הבא:

-   כל הצגה תהיה 10 דק׳ עם 5 דק׳ לשאלות. אני מבקש לשמור על הזמן כיוון שכולם צריכים להציג, מי שיחרוג מהזמן יצטרך לעצור ולא יהיה זמן לשאלות. אז בבקשה תתכוננו על ההצגה לפני השיעור כדי לעמוד בזמנים.

-   עליכם להציג [**התקדמות**]{.underline} בנושא הפרויקט שהגשתם בתחילת הקורס על ידי עיבוד מתקדם יותר של הנתונים, הוספת מקורות דיגיטליים והעשרתם בתיוגים, או ויזואליזציות של דפוסים מעניינים.

-   ההצגה תהיה בפורמט של [**כרזה מדעית (פוסטר)**]{.underline}, להוראות מדויקות והסבר על אופן ניקוד העבודה ראו מטה. דוגמא של כרזה [נמצאת כאן](https://docs.google.com/presentation/d/1IKUFkpl94C9jXB0n7jUuMMshQHkwdQVmLZiMZN7qG5o/edit?usp=sharing). כמובן שאתם יכולים גם להכין אחת בעצמכם ו/או לעצב אותה באמצעות תוכנה כגון [Canva](https://www.canva.com/posters/templates/research/).

## כרזה מדעית

### מועד הגשה: 28/02/2025

לאחר ההצגה בכיתה ופידבק שתקבלו ממני ומחבריכם לספסל הלימודים תוכלו לעבוד ולשפר את תוצאות הפרויקט שלכם ולהגיש [כרזה מדעית מעודכנת של המחקר, תוצאותיו, ניתוח ומסקנות]{.underline} כחודש לאחר סיום הסמסטר. את הכרזה הסופית וקובץ נתונים עם דוגמאות לחומרים הדיגיטליים של המחקר שלכם **יש להעלות [לטופס בקישור כאן](https://forms.gle/jnYxWsqG3ha5q6JV9){target="_blank"}**.

הכרזה המדעית תציג באופן תמציתי את עיקרי עבודת המחקר. ראו [תבנית בקישור הבא](https://docs.google.com/presentation/d/1IKUFkpl94C9jXB0n7jUuMMshQHkwdQVmLZiMZN7qG5o/edit?usp=sharing){target="_blank"}

ראו דוגמאות משנה קודמת [בקישור הבא](https://docs.google.com/document/d/1GhtQd-u2dWz-21XEL8IBd3sYjToIG8-m/edit?usp=sharing&ouid=105840067147853910357&rtpof=true&sd=true){target="_blank"}.

1.  [גודלה של הכרזה המדעית]{.underline}: 70\*100 ס"מ.

<!-- -->

2.  הכותרת מאירת עיניים ומסקרנת, במרחב הכרזה חלוקה בלתי עמוסה של תכניה, הניסוחים המילוליים קצרים, שילוב רכיבים חזותיים באופן ברור.

<!-- -->

3.  [מבנה הכרזה המדעית]{.underline}: 

-   בראש הכרזה: כותרת של נושא/שאלת המחקר + שמות המבצעים + שם מכון המחקר בחסותו בוצעה העבודה. 

-   במרחב הכרזה המדעית - פריסה גרפית מיטבית: 

    -   תקציר הכולל את מטרות ושאלת החקר 

    -   רקע מדעי 

    -   מקורות ושיטות (כולל תמונות)

    -   תוצאות המאורגנות בטבלאות וגרפים

    -   דיון ומסקנות

[קריטריונים להערכת הכרזה המדעית]{.underline}: 

**כותרת מאירת עיניים** - מתאפשרת קריאת התכנים ממרחק של 1 מטר, שמירה על רצף הגיוני בין מרכיבי הכרזה.

**מאפיינים חזותיים** - עיצוב אסתטי, חלוקה בלתי עמוסה של תכנים, ייצוג התכנים בדרכים מגוונות (תמונות, תרשימים, גרפים), איזון חזותי בין מרכיבי הכרזה, יצירתיות ומקוריות.

**מאפיינים תוכניים** - הימצאות של כל מרכיבי הכרזה, דיוק בתכנים המדעיים, הקפדה על כותרות ויחידות מידה בטבלאות ובגרפים, ניסוחים מילוליים תמציתיים. 
